version: '3'

  ## To run these tests you must export the environment variables in /factory/.env with `set -a && . ../.env && set +a`

services:

  test-factory-cypress:
    env_file:
      - .env
    build:
      args:
        CYPRESS_VERSION: ${CYPRESS_VERSION}
        CHROME_VERSION: ${CHROME_VERSION}
        BASE_TEST_IMAGE: cypress/factory:${FACTORY_VERSION}
      dockerfile: Dockerfile
      context: .
    command:
      cypress run -b chrome