# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  node: circleci/node@5.2.0

# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
jobs:
  cypress-test-factory:
    machine:
      image: ubuntu-2204:2024.04.4
    steps:
      - checkout
      - run:
          name: building docker image
          command: |
            docker compose up
            docker container cp project-test-factory-cypress-1:/opt/app/cypress/reports/ /home/circleci/project/factory/container
          working_directory: factory
      - store_test_results:
          path: /home/circleci/project/factory/container/
      - store_artifacts:
          path: /home/circleci/project/factory/container/
          destination: artifact-file

  smoke-test:
    machine:
      image: ubuntu-2204:2024.04.4
    steps:
      - checkout
      - run: chmod +x .circleci/install_telegraf.sh
      - run:
          name: Install Telegraf
          command: .circleci/install_telegraf.sh
      - run:
          name: start telegraf
          command: telegraf --config https://eu-central-1-1.aws.cloud2.influxdata.com/api/v2/telegrafs/0d1acfba36db3000
          background: true
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test-smoke
      - run: chmod +x .circleci/send_to_telegraf.sh
      - run:
          name: Post to telegraf
          command: .circleci/send_to_telegraf.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - cypress-test-factory
      - smoke-test:
          requires:
            - cypress-test-factory